### ISSUE TITLE
Resizing Application 

### ISSUE THREAD

**Issue by Abdiy0** [nourinjh/EECS2311#64]
Product: VennDiagramFX.4.jar
Platform: Accer Desktop
OS: Windows 10
Release tested: V2
Java version: 8
Issue Description:
When I try to make the windows bigger, the application should resize to fit the full school

Expected Results:
the window should [resize] to full screen

Actual results:
The window does not auto resize

![0](https://user-images.githubusercontent.com/46433229/76696296-2745c980-6660-11ea-9b35-6d58891a7dcf.png)

**Comment by AndrewHocking** [comment]
https://github.com/nourinjh/EECS2311/issues/41
