### ISSUE TITLE
(Bug) Venn Circle Intersection Color Change

### ISSUE THREAD

**Issue by sarwat12** [nourinjh/EECS2311#66]
**OS used:** Linux
**Release tested:** Latest Release 2.0
**Java Version:** Java 12
**Description:** The color changing option in the settings tab of the UI for the intersecting area of the circle does not produce the desired color change.
**Severity:** Normal
**Priority:** P3

**Steps to reproduce:**
1 - Open Venn application
2 - Click on the settings tab towards the left of the Venn circles
3 - Scroll down towards the bottom, where there is a drop down menu to change the color of the intersection
4 - Click on a desired color for the intersection

**Actual Results:** No color change
**Expected Results:** Color of the intersection changing to the desired color

**Comment by AndrewHocking** [comment]
The setting changes the colour of the text, not the colour of the background. Are you not seeing the text colour change colour?

**Comment by AndrewHocking** [comment]
A setting to change the colour of the background of the intersection has been added in development and will be available next release. I have not been able to see any issues with the text colour in any of my testing, so I'm considering this issue closed.
