### ISSUE TITLE
(Bug) Export to image feature

### ISSUE THREAD

**Issue by sarwat12** [nourinjh/EECS2311#67]
**OS used:** Linux
**Release tested:** Latest Release 2.0
**Java Version:** Java 12
**Description:** The **export to image** feature option seems to take a screenshot of the entire window instead of the Venn diagram.
**Severity:** Minor
**Priority:** P4

**Steps to reproduce:**
1 - Open Venn application
2 - Click on the **Export to Image** tab towards the left of the Venn circles
3 - Inspect the screenshot produced by the application

**Actual Results:** An image of the everything present in the window at the time of the feature being used 
**Expected Results:** An image of just the application, including the state of the circles

**Comment by AndrewHocking** [comment]
Could you please provide an example of a screenshot you've taken that has this bug? I don't seem to have this issue on my end.

**Comment by AndrewHocking** [comment]
Also what is your screen resolution?

**Comment by AndrewHocking** [comment]
I've redone the screenshot functionality anyway, so this bug likely no longer exists
