### ISSUE TITLE
Program throws an exception when a user tries to open an existing Venn diagram, and exits out of the FileChooser window that pops up

### ISSUE THREAD

**Issue by A-Chidalu** [nourinjh/EECS2311#69]
# Group 4 Venn Bug Report 1

### Summary: Program throws an exception when a user tries to open an existing Venn diagram, and exits out of the FileChooser window that pops up

Product: Venn [Group 4]

Version: Prototype Project Submission Release [Released on March 8th, 2020]

Component: MenuBar> File> Open > Ok > Exit out of FileChooser

Platform: 
-Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 1.99Ghz
-RAM: 16GB
-System Type: 64-bit Operating System, x64-based processor

OS: Windows 10 Home

Severity: Normal 

Priority: P3 (Normal Priority)

Full Description:

	Steps To Reproduce: 
		1. Open Venn using java -jar Venn.jar
		2. In the top left corner of the screen click File
		3. Click Open, Or alternatively click Ctrl + O
                4. When the FileChooser Window Pops up, Do not select any file and click the X button in the top right
                5. Notice as an exception pops up 
 

	Actual Results:An exception stack trace is thrown
	
	Expected Results: No exception stack trace should have been thrown, I should have been led back to the application

	Build & Date: Venn Release 2, encountered on March 15th, 2020

## Photo of the Exception that was thrown
![image](https://user-images.githubusercontent.com/50505942/76706020-d4e5c680-66ba-11ea-8169-e5c01ffb996c.png)

![image](https://user-images.githubusercontent.com/50505942/76706039-03fc3800-66bb-11ea-8f5e-b7ecb87ba353.png)

**Comment by AndrewHocking** [comment]
Fixed in development, fix will be available in next release
