### ISSUE TITLE
When Trying to Save the application, if you don't save anything and just close the FileChooser Window, an Exception is thrown. 

### ISSUE THREAD

**Issue by A-Chidalu** [nourinjh/EECS2311#70]
# Group 4 Venn Bug Report 2

### Summary:  When Trying to Save the application, if you don't save anything and just close the FileChooser Window, an Exception is thrown. 

Product: Venn [Group 4]

Version: Prototype Project Submission Release [Released on March 8th, 2020]

Component: Save Button Right Under the List View

Platform: 
-Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 1.99Ghz
-RAM: 16GB
-System Type: 64-bit Operating System, x64-based processor

OS: Windows 10 Home

Severity: Normal 

Priority: P3 (Normal Priority) These Exceptions Can Simply be caught

### Full Description:

	Steps To Reproduce: 
		1. Open Venn using java -jar Venn.jar
		2. In the Left Side of the screen Click save
                3. Click Ok to The unsaved Changes popup
                4. Without Choosing a location to save the application just click X on the FIleChooser Popup
                5. Notice as an Exception is thrown

 

	Actual Results :An exception stack trace is thrown
	
	Expected Results: No exception stack trace should have been thrown, I should have been led back to the application

	Build & Date: Venn Release 2, encountered on March 15th, 2020

## Photo of the Exception 

![image](https://user-images.githubusercontent.com/50505942/76706663-91da2200-66bf-11ea-899f-e190d20a297f.png)

**Comment by AndrewHocking** [comment]
https://github.com/nourinjh/EECS2311/issues/69
