### ISSUE TITLE
(Bug) Item placed outside circle does not go back into the text list

### ISSUE THREAD

**Issue by Jihal** [nourinjh/EECS2311#73]
Bug Description: Item placed outside the circle is not visible
OS Used: macOS Catalina Version 10.15.3
Java Version: 8 Update 241 (build 1.8.0_241-b07)
Release: Peer Assessment 3 
Severity: Normal
Priority: P3

Steps to Reproduce: 
1. Open Venn Application
2. Add text containing any info
3. Place the item outside the circle near venn diagram subtitles

Actual Results: The item placed outside the circle is not visible and does not go back into the text list. However, the item is still in the same placed location just not visible under any background colour. 

Expected Results: The item goes back to the text box list upon accidental placement of text outside the circle.

**Comment by AndrewHocking** [comment]
Issue has been fixed in development, will be fixed for next release
