### ISSUE TITLE
(Enhancement): Make contents resize alongside window

### ISSUE THREAD

**Issue by Jihal** [nourinjh/EECS2311#74]
Enhancement Description: Make contents inside window resize alongside window.
OS Used: macOS Catalina Version 10.15.3
Java Version: 8 Update 241 (build 1.8.0_241-b07)
Release: Peer Assessment 3 

Steps to view possible enhancement idea: 
1. Open Venn Application
2. Resize window 

Actual Results: The window resizes but the contents inside the window do not resize accordingly. 

Future Results: The contents inside the window resizes alongside the window.

**Comment by AndrewHocking** [comment]
https://github.com/nourinjh/EECS2311/issues/41
https://github.com/nourinjh/EECS2311/issues/64
