### ISSUE TITLE
Saving two venn files

### ISSUE THREAD

**Issue by NooryA** [nourinjh/EECS2311#78]
Product: Venn.jar
Version: Midterm
Platform: HP Spectre x 360 15-inch
OS: Windows 10
Java Version: 1.8.0
Severity: Normal
Priority: P1

Description:
Not able to save two venn files using the save button. The program can only save once

Steps to reproduce:
- Fix the "save" button and allow the program to save twice

Actual Result:
- Program can't be saved more than once

Expected Result:

- Program should be able to be saved as many times as wanted by the user
Build Date & Platform:

March 15th, 2020
HP Spectre x 360 15-inch

**Comment by AndrewHocking** [comment]
What do you mean it can't be saved more than once? Does nothing happen when you hit the save button the second time? Does it show the save dialogue but not actually save? I don't see this issue on my end.
