### ISSUE TITLE
Dragging the text boxes outside the circles

### ISSUE THREAD

**Issue by NooryA** [nourinjh/EECS2311#79]
Product: Venn.jar
Version: Midterm
Platform: HP Spectre x 360 15-inch
OS: Windows 10
Java Version: 1.8.0
Severity: Normal
Priority: P2

Description:
Dragging the text boxes outside the circles makes the text boxes disappear because of the black color but is still there there. 

Steps to reproduce:
- Change the color of the background

Actual Result:

- Text boxes disappear when dragged outside circle

Expected Result:

- Text boxes should be visible to the user when dragged outside circle

Build Date & Platform:

March 15th, 2020
HP Spectre x 360 15-inch

**Comment by AndrewHocking** [comment]
https://github.com/nourinjh/EECS2311/issues/73
